 <h3 style="color:yellow;background-color:red;padding:10px;width:fit-content">Bag of Words(BOW)</h3>

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.DataFrame({"text":["People watch ML",
                           "People watch DL people",
                           "People write comments",
                           "People works"],
                           "outputs":[1,1,0,0]})
df

                     text  outputs
0         People watch ML        1
1  People watch DL people        1
2   People write comments        0
3            People works        0

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [17]:
bow = cv.fit_transform(df['text'])

In [18]:
# vocabulary --> Assign index numbers
print(cv.vocabulary_)
# comments gets 0 index number, and so on

{'people': 3, 'watch': 4, 'ml': 2, 'dl': 1, 'write': 6, 'comments': 0, 'works': 5}

In [19]:
bow.toarray()
'''
array([[0, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 2, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In first row first element 0 -> comments so first sentence does not have comment word,
in first row second element 0 -> dl so first sentence does not have dl
in first row third element 1 -> ML so yes present 1 time 
and so on do for all
'''

'\narray([[0, 0, 1, 1, 1, 0, 0],\n       [0, 1, 0, 2, 1, 0, 0],\n       [1, 0, 0, 1, 0, 0, 1],\n       [0, 0, 0, 1, 0, 1, 0]], dtype=int64)\n\nIn first row first element 0 -> comments so first sentence does not have comment word,\nin first row second element 0 -> dl so first sentence does not have dl\nin first row third element 1 -> ML so yes present 1 time \nand so on do for all\n'

In [20]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 1 1 0 0]]
[[0 1 0 2 1 0 0]]
[[1 0 0 1 0 0 1]]

In [28]:
# Provide new data
cv.transform(["Talha watch ML"]).toarray()

array([[0, 0, 1, 0, 1, 0, 0]], dtype=int64)

In [32]:
X = bow.toarray()
y= df["outputs"]

<h4 style="color:green">N-grams</h4>

In [33]:
# N-gram is nothing but here if we put n-gram = 2 so 2 word is consider as one token
# People watch ML. So it take People Watch is one token and Watch ML is as another token

df = pd.DataFrame({"text":["People watch ML",
                           "People watch DL people",
                           "People write comments",
                           "People works"],
                           "outputs":[1,1,0,0]})
df

                     text  outputs
0         People watch ML        1
1  People watch DL people        1
2   People write comments        0
3            People works        0

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [35]:
bow = cv.fit_transform(df['text'])

In [36]:
# vocabulary --> Assign index numbers
print(cv.vocabulary_)

{'people watch': 1, 'watch ml': 5, 'watch dl': 4, 'dl people': 0, 'people write': 3, 'write comments': 6, 'people works': 2}

In [37]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 0 0 0 1 0]]
[[1 1 0 0 1 0 0]]
[[0 0 0 1 0 0 1]]

<h3 style="color:red;background-color:yellow;padding:10px;width:fit-content">TF-IDF(Term frequency-Inverse document frequency)</h3>

In [ ]:
# it use formula for text to numeric conversion and that formula is:
# Wx,y = tf(x,y) * log (N/df(x))
# Wx,y = weight of term x in document y and N is total number of documents

import pandas as pd
import numpy as np
df = pd.DataFrame({"text":["People watch ML",
                           "People watch DL people",
                           "People write comments",
                           "People works"],
                           "outputs":[1,1,0,0]})
df

                     text  outputs
0         People watch ML        1
1  People watch DL people        1
2   People write comments        0
3            People works        0

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [4]:
arr = tfid.fit_transform(df['text']).toarray()

In [5]:
arr

array([[0.        , 0.        , 0.72664149, 0.37919167, 0.5728925 ,
        0.        , 0.        ],
       [0.        , 0.60735961, 0.        , 0.63389088, 0.4788493 ,
        0.        , 0.        ],
       [0.66338461, 0.        , 0.        , 0.34618161, 0.        ,
        0.        , 0.66338461],
       [0.        , 0.        , 0.        , 0.46263733, 0.        ,
        0.88654763, 0.        ]])

In [ ]:
print(tfid.idf_) # idf_ represent the inverse document frequency which tells how each word is important.

[1.91629073 1.91629073 1.91629073 1.         1.51082562 1.91629073
 1.91629073]

<h3 style="color:green;background-color:white;padding:10px;width:fit-content">Word2Vec</h3>

In [16]:
import numpy as np
import pandas as pd
# Try with tab delimiter
df = pd.read_csv("001ssb.txt", sep="\t", header=None)

# Or if space-separated
# df = pd.read_csv("001ssb.txt", delim_whitespace=True, header=None)

print(df.head())

                                                   0
0                                 A Game Of Thrones
1                Book One of A Song of Ice and Fire
2                            By George R. R. Martin
3                                          PROLOGUE
4  We should start back, Gared urged as the woods...

In [1]:
!pip install gensim nltk

Requirement already satisfied: gensim in c:\users\dell  r\appdata\roaming\python\python312\site-packages (4.3.3)
Requirement already satisfied: nltk in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (3.9.1)
Requirement already satisfied: numpy<2.0,>=1.18.5 in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in c:\users\dell  r\appdata\roaming\python\python312\site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from gensim) (7.3.1)
Requirement already satisfied: click in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2024.7.24)
Requirement already satisfied: tqdm in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: wrapt in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from smart-open>=1.8.1->gensim) (1.16.0)
Requirement already satisfied: colorama in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)

WARNING: Ignoring invalid distribution ~ip (C:\Users\dell  R\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\dell  R\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\dell  R\AppData\Local\Programs\Python\Python312\Lib\site-packages)

In [17]:
# word2Vec is inside genism library
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
from gensim.models import Word2Vec
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\dell
[nltk_data]     R\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [18]:
with open("001ssb.txt", "r", encoding="utf-8") as f:
    text = f.read()

# Tokenize into words
story = simple_preprocess(text)

# Show first 50 story
print(story[:50])

# Total number of story
print("Total story:", len(story))

['game', 'of', 'thrones', 'book', 'one', 'of', 'song', 'of', 'ice', 'and', 'fire', 'by', 'george', 'martin', 'prologue', 'we', 'should', 'start', 'back', 'gared', 'urged', 'as', 'the', 'woods', 'began', 'to', 'grow', 'dark', 'around', 'them', 'the', 'wildlings', 'are', 'dead', 'do', 'the', 'dead', 'frighten', 'you', 'ser', 'waymar', 'royce', 'asked', 'with', 'just', 'the', 'hint', 'of', 'smile', 'gared']
Total story: 284700

In [19]:
# i want to see first sentence
story[0]

'game'

In [29]:
# Intialize model
model = Word2Vec(vector_size=100, window=5, min_count=1)

In [30]:
model.build_vocab(story) # it will create vocab of all words in story

In [31]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs) # it will train the model

(997821, 6030555)

In [ ]:
if "Mormont" in model.wv.key_to_index:
    print(model.wv.most_similar("Mormont"))
else:
    print("Mormont not found in vocabulary")

Mormont not found in vocabulary

In [ ]:
model.wv.similarity("arya","sansa") # relation between 2 characters in stroy

KeyError: "Key 'arya' not present"

In [34]:
model.wv["deep"].shape

KeyError: "Key 'deep' not present"

In [60]:
model.wv.get_normed_vectors().shape

(26, 100)

In [61]:
y = model.wv.index_to_key

In [62]:
len(y)

26

In [63]:
y

['e',
 't',
 'o',
 'a',
 'h',
 'n',
 'r',
 's',
 'i',
 'd',
 'l',
 'w',
 'u',
 'm',
 'g',
 'y',
 'f',
 'c',
 'b',
 'p',
 'k',
 'v',
 'j',
 'q',
 'z',
 'x']

In [35]:
vec = model.wv.get_normed_vectors()

In [36]:
vec

array([[-0.02721166,  0.1042969 ,  0.0729077 , ..., -0.01799762,
         0.17726912,  0.00474436],
       [-0.06660024,  0.04537209,  0.062216  , ...,  0.07789962,
        -0.11821554,  0.22710878],
       [ 0.10270501,  0.00304913,  0.00434518, ...,  0.04806784,
         0.19968018, -0.07458708],
       ...,
       [ 0.09891544,  0.02372628, -0.1445784 , ...,  0.12176228,
        -0.01635435,  0.21701281],
       [-0.06980902, -0.12086083,  0.00236008, ..., -0.07454813,
        -0.09668199,  0.01992953],
       [ 0.05691979,  0.01290159,  0.03126357, ...,  0.05171029,
        -0.0942157 ,  0.27190456]], dtype=float32)

In [37]:
# If we want to see graphically so we use dimensionally reduction like PCA
from sklearn.decomposition import PCA

In [38]:
pca = PCA(n_components=3)

In [39]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [55]:
import numpy as np
X
y = np.array([i for i in range(len(X))])

In [56]:
X.shape

(26, 3)

In [57]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (6.3.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from plotly) (2.5.0)
Requirement already satisfied: packaging in c:\users\dell  r\appdata\local\programs\python\python312\lib\site-packages (from plotly) (24.1)

WARNING: Ignoring invalid distribution ~ip (C:\Users\dell  R\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\dell  R\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\dell  R\AppData\Local\Programs\Python\Python312\Lib\site-packages)

In [ ]:
# from here we can see 3 dimension so we can use 3D plot and also relationship among grammetical and characters
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2,color=y[200:300])
fig.show()
# check below github for complete information and code

# https://github.com/entbappy/Generative-AI-Mastery-Resources/blob/main/Data%20Preprocessing%20and%20Embeddings/Text-Representation_Word%20Embeddings-2.ipynb